### ISSUE TITLE
Suggestion: Trigger the voice conversion separately?

### ISSUE THREAD

**Issue by MarkMad** [Spectre-hidN/LibRead-Tool#2]
Love the app. Is there a way to trigger the voice conversion separately? I would like to make edits to the text file sometimes.

**Comment by AdityaDa5** [comment]
Added a workaround in [ac0c500](https://github.com/Spectre-hidN/LibRead-Tool/commit/ac0c5006ef86db1686abeaf7c867b0436459393c).

You can now choose not to replace the recently scrapped contents inside the part files by disabling the `replacePartContents` option in the config file.
Run LibRead-Tool with the convert-text-to-speech option disabled. Modify the text files and again re-run the tool but this time enable the convert-text-to-speech option.
Will be releasing V2 binaries soon.

**Comment by MarkMad** [comment]
Thanks!
